version: '3.4'

services:
  api:
    container_name: api
    build: .
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - seq

  seq:
    container_name: seq
    image: datalust/seq
    ports:
      - "8000:80"
    environment:
      ACCEPT_EULA: Y